services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    volumes:
      - ./src:/var/www/html
    image: nginx:alpine
    ports:
      - "8080:80"
    networks:
      - internal
  php:
    build: ./.docker/php
    networks:
      - internal
    volumes:
      - ./src:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=docker-cli-nginx"
networks:
  internal:
    driver: bridge